version: 2.1
executors:
  gradle-executor:
    docker:
      - image: circleci/openjdk:11-jdk

jobs:
  build:
    executor: gradle-executor
    steps:
      - checkout

      # Setup JDK and Gradle
      - run:
          name: Setup JDK and Gradle
          command: |
            echo 'export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64' >> $BASH_ENV
            echo 'export PATH=$JAVA_HOME/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV
            curl -s "https://get.sdkman.io" | bash
            source "$HOME/.sdkman/bin/sdkman-init.sh"
            sdk install gradle

      # Build the project
      - run:
          name: Build the project
          command: gradle build

  test:
    executor: gradle-executor
    steps:
      - checkout

      # Setup JDK and Gradle (same as in the 'build' job)

      # Run tests
      - run:
          name: Run tests
          command: gradle test
