version: 2.1
executors:
  gradle-executor:
    docker:
      - image: circleci/openjdk:11-jdk-browsers

jobs:
  build:
    executor: gradle-executor
    steps:
      - checkout

      # Build the project
      - run:
          name: Build the project
          command: gradle build

  test:
    executor: gradle-executor
    steps:
      - checkout

      # Run tests
      - run:
          name: Run tests
          command: gradle test